import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/contexts/AuthProvider";
import Providers from "@/contexts/Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Jobber by Avanti",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-[#191919]`}>
            <Providers>
                <Toaster />
                <AuthProvider>
                {children}
                </AuthProvider>
            </Providers>
          </body>
        </html>
  );
}
