import { BonusData } from './Bonus';
import { CustomerData } from './Customer';
import { PackageData } from './Package';
import { ProjectData } from './Project';
import { RequestData } from './Request';
import { StatusData } from './Status';
import { UserData } from './User';

export type JobData = {
  id: number;
  customer: CustomerData;
  project: ProjectData | null;
  package: PackageData | null;
  requester: UserData;
  responsible: UserData;
  user_created: UserData;
  status: StatusData;
  bonus: BonusData | null;
  request: RequestData;
  followers: number[];
  title: string;
  briefing: string;
  estimated_time: number;
  package_consumption: number;
  minutes_per_day: number;
  qtd_days: number;
  budget: boolean;
  package_date: string | null;
  start: string;
  finish: string | null;
  is_finished: boolean;
  internal_term: string;
  customer_term: string;
  date_created: string;
  date_updated: string;
  publication_date: string | null;
};
export type JobPostData = {
  customer: number;
  project?: number;
  package?: number;
  requester: number;
  responsible: number;
  status: number;
  bonus: number | null;
  request: number;
  followers: number[];
  title: string;
  briefing: string;
  estimated_time: number;
  package_consumption: number;
  minutes_per_day: number;
  qtd_days: number;
  budget: boolean;
  package_date?: string | Date;
  start: string;
  internal_term: string;
  customer_term: string;
  publication_date: string | null;
};
export type JobPutData = JobPostData & { id: number };
export type JobPatchStatusData = Pick<JobData, 'id'> & { status: number };
export type JobPatchFollowersData = Pick<JobData, 'id' | 'followers'>;
